変更しました
prog-g/webDesigner-course pull request #3
Opened 2021-04-03 14:47 UTC by Kotaro-Hamu

言語を変更 cssの見た目変更

2021-04-03 14:47 UTC, yuuichi-exjsb approved these changes, later dismissed

2021-04-03 15:16 UTC, curegit requested changes
変更ありがとう

`h1 {`
みたいに { のまえにスペースが欲しいのと
CSSファイル最後に改行がないのでいれてほしいです

2021-04-04 01:31 UTC, Kei01234 commented
@Kotaro-Hamu おれの方で残りの整形作業はやっておいた！

追加でindex.htmlの6行目に`<meta name="viewport" content="width=device-width, initial-scale=1.0">`を追加しておきました。スマホで見やすくするため。

2021-04-04 01:32 UTC, Kei01234 approved these changes

2021-04-04 01:34 UTC, Kei01234 approved these changes

2021-04-04 01:34 UTC, merged