新歓で使うファイルを作成
prog-g/webDesigner-course pull request #5
Opened 2021-04-04 05:00 UTC by Kei01234

穴埋め形式のhtmlファイルを作成しました。
また、html内で使用予定の画像も追加アップロードしておきます。

2021-04-04 05:13 UTC, yuuichi-exjsb submitted a review, later dismissed
ありがとう！！

2021-04-04 06:10 UTC, curegit requested changes
また整形がおかしいので直してほしいです 📝

2021-04-04 06:10 UTC, curegit commented on welcomeEvent/index.html
> +</html>
テキストファイル末尾は改行いれましょう

2021-04-12 10:10 UTC, Kei01234 commented
CSSのインデントを整えました。また、body内のhtmlを全削除しました。

2021-04-12 10:18 UTC, merged